### ISSUE TITLE
Issues related to Child Resources having no owner references

### ISSUE THREAD

**Issue by neowulf** [vmware-labs/reconciler-runtime#488]
### Describe the bug

When creating children in a namespace different than the resource's namespace - the owner references can't be used. In such cases, OurChild func needs to be implemented. Under these circumstances,

1. the tracked children get created more than once when the resource is created / updated.
1. the tracked children are not deleted when the resource is deleted.

### Reproduction steps

.

### Expected behavior

.

**Comment by nebhale** [comment]
I believe you're supposed to implement the [`ListOptions`](https://github.com/vmware-labs/reconciler-runtime/blob/main/reconcilers/child.go#L123-L132) function here.

**Comment by scothis** [comment]
Yea, the intent is to implement `ListOptions` to override the default value. I do think there's something we can do to make this case more discoverable rather than being surprised by resources being created en masse and not cleaned up. A few possible approaches:

1. change the default `ListOptions` when `SkipOwnerReference` is true (what you proposed in #489)
2. require the user to specify `ListOptions` when `SkipOwnerReference` is true
3. deprecate `ListOptions`

Assuming there is an informer defined for the child resource, using `ListOptions` isn't much faster than the equivalent `OurChild` resource. It does make a difference if the `List` client request actually hits the API server.

Option 2 feels like a good middle ground. It will be a breaking change for users who only operate in the same namespace but don't want to use owner refs (I'm not sure why someone would need that).  The reconciler will fail fast at startup rather than spam the API server with orphaned resources.

What do you think?

**Comment by mamachanko** [comment]
> 1. change the default `ListOptions` when `SkipOwnerReference` is true (what you proposed in [Child Resources having no owner references are created more than once #489](https://github.com/vmware-labs/reconciler-runtime/pull/489))
> 2. require the user to specify `ListOptions` when `SkipOwnerReference` is true
> 3. deprecate `ListOptions`
> 
> [...]
> 
> Option 2 feels like a good middle ground. It will be a breaking change for users who only operate in the same namespace but don't want to use owner refs (I'm not sure why someone would need that). The reconciler will fail fast at startup rather than spam the API server with orphaned resources.
> 
> What do you think?

➕→2️⃣
